import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const OUT_DIR = '/mnt/project-files/poe-arcade/vendor/fonts';
const CSS_OUT = '/mnt/project-files/poe-arcade/shared/fonts.css';
fs.mkdirSync(OUT_DIR, { recursive: true });

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// family spec -> css2 query fragment
const FAMILIES = [
  ['IM Fell English',      'ital@0;1'],
  ['IM Fell English SC',   ''],
  ['Cormorant Garamond',   'ital,wght@0,300;0,400;0,500;0,600;0,700;1,400'],
  ['EB Garamond',          'ital,wght@0,400..800;1,400..700'],
  ['Pirata One',           ''],
  ['UnifrakturMaguntia',   ''],
  ['Special Elite',        ''],
  ['Cinzel',               'wght@400..900'],
  ['Cinzel Decorative',    'wght@400;700;900'],
  ['Playfair Display',     'ital,wght@0,400..900;1,400..700'],
  ['Marcellus SC',         ''],
  ['Spectral',             'ital,wght@0,300;0,400;0,500;0,600;0,700;1,400'],
  ['JetBrains Mono',       'ital,wght@0,100..800;1,100..800'],
  ['Old Standard TT',      'ital,wght@0,400;0,700;1,400'],
];

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

function curl(url, binOut) {
  const args = ['-sSL', '--max-time', '90', '-A', UA];
  if (binOut) args.push('-o', binOut, '-w', '%{http_code}');
  args.push(url);
  return execFileSync('curl', args, { encoding: binOut ? 'utf8' : 'utf8', maxBuffer: 64 * 1024 * 1024 });
}

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

let out = [];
out.push('/* poe-arcade — shared/fonts.css');
out.push(' * Self-hosted Google Fonts. Generated by tools/fetch-fonts.mjs.');
out.push(' * fonts.googleapis.com / fonts.gstatic.com are NOT reachable from inside the');
out.push(' * browser in this environment, so every face below is vendored under');
out.push(' * /vendor/fonts/ and referenced with a ROOT-RELATIVE url(). Link this file');
out.push(' * from a game with: <link rel="stylesheet" href="/shared/fonts.css">');
out.push(' * Subsets kept: latin, latin-ext. All faces use font-display:swap.');
out.push(' */');
out.push('');

let files = 0, faces = 0;
const summary = [];

for (const [family, query] of FAMILIES) {
  const famParam = family.replace(/ /g, '+') + (query ? ':' + query : '');
  const url = `https://fonts.googleapis.com/css2?family=${famParam}&display=swap`;
  let css;
  try { css = curl(url); } catch (e) { console.error('CSS FAIL', family, e.message); continue; }
  if (!/@font-face/.test(css)) { console.error('NO FACES', family, css.slice(0, 200)); continue; }

  // css2 emits: /* subset */\n@font-face{...}
  const blocks = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  let kept = 0;
  const chunks = [];
  for (const [, subset, block] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) continue;
    const src = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/);
    if (!src) continue;
    const remote = src[1];
    const style = (block.match(/font-style:\s*([^;]+);/) || [, 'normal'])[1].trim();
    const weight = (block.match(/font-weight:\s*([^;]+);/) || [, '400'])[1].trim();
    const ext = path.extname(new URL(remote).pathname) || '.woff2';
    const local = `${slug(family)}-${style}-${weight.replace(/\s+/g, '_')}-${subset}${ext}`;
    const dest = path.join(OUT_DIR, local);
    if (!fs.existsSync(dest)) {
      const code = curl(remote, dest);
      if (code.trim() !== '200') { console.error('FONT FAIL', local, code); fs.rmSync(dest, { force: true }); continue; }
      files++;
    }
    const rewritten = block
      .replace(/url\(https:\/\/fonts\.gstatic\.com\/[^)]+\)/, `url("/vendor/fonts/${local}")`)
      .replace(/@font-face\s*\{/, '@font-face {\n ')
      .replace(/;\s*/g, ';\n  ')
      .replace(/\n\s*\}/, '\n}');
    chunks.push(`/* ${family} — ${subset} */\n${rewritten}`);
    kept++; faces++;
  }
  if (kept) { out.push(chunks.join('\n')); out.push(''); }
  summary.push(`${family}: ${kept} faces`);
  console.log(`  ${family.padEnd(22)} ${kept} faces`);
}

fs.writeFileSync(CSS_OUT, out.join('\n'));
console.log(`\nTOTAL: ${faces} @font-face rules, ${files} woff2 files downloaded`);
